# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://jekyll-bk-base.netlify.app/

media_folder: "assets/images"

collections:
  - name: "config"
    label: "Config"
    create: true
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Nav main Items"
            name: "main"
            widget: "list"
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Link, name: url, widget: string }
          - label: "Nav footer Items"
            name: "footer"
            widget: "list"
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Link, name: url, widget: string }
      
      - label: "Contact"
        name: "contact"
        delete: false
        file: "_data/contact.yml"
        fields:
          - { label: Email, name: email, widget: string, required: false }
          - { label: Téléphone, name: phone, widget: string, required: false }
          - label: "Adresse Items"
            name: "adresses"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Rue, name: rue, widget: string, required: false }
              - { label: "Code postal", name: cp, widget: string, required: false }
              - { label: Ville, name: ville, widget: string, required: false }
              - { label: Départment, name: department, widget: string, required: false }
              - { label: Région, name: region, widget: string, required: false }
              - { label: Pays, name: pays, widget: string, required: false }
          - label: "Réseaux sociaux"
            name: "socials"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
      
      - label: "Infos"
        name: "infos"
        file: "_data/infos.yml"
        fields:
          - label: "Horaires d'ouvertures"
            name: "horaires"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Début, name: debut, widget: string, required: false }
              - { label: Fin, name: fin, widget: string, required: false }

  #-----------------------------#
  #---- Les posts - Articles ---#
  #-----------------------------#
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "mes_collections/_posts"
    sort: "date:asc" # Default is title:asc
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{year}}/{{month}}/{{day}} -- {{title}}"
    create: true # Allow users to create new documents in this collection

    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {label: "Cover Image", name: "cover_url", widget: "image", tagname: '', required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Author", name: "author", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["blog"], required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  #------------------#
  #---- Les pages ---#
  #------------------#
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: >
      Toutes les pages.
    folder: "_pages"
    sort: "date:asc" # Default is title:asc
    slug: "{{slug}}"
    summary: "{{title}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #---- Les categories ---#
  - name: "categories"
    label: "Categories"
    label_singular: "Categorie"
    description: >
      Toutes les categories.
    folder: "mes_collections/_categories"
    sort: "date:asc" # Default is title:asc
    slug: "{{slug}}"
    summary: "{{title}}"
    create: true

    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {label: "Layout", name: "layout", widget: "string", default: "categorie"}
